version: '3'
services:
  logistica11:
    build: .
    ports:
      - "5003:5003"
    environment:
      POSTGRES_URL: postgresql+psycopg2://admin:admin@offersdb:5432/OffersDB
      SECRET_KEY: nativa2023
      AMBIENTE: produccion
    restart: always
    depends_on:
      - offersdb
    networks:
      - offers_network
  offersdb:
    image: postgres
    environment:
      POSTGRES_DB: OffersDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    networks:
      - offers_network

networks:
  offers_network:
    driver: bridge